name: ETL informeseguridadcnsgobmx

on:
  schedule:
    - cron: '0 18 * * 1-5' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para permitir git pull

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python main.py

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sincronizar con cambios remotos
        run: |
          git pull --rebase origin main

      - name: Hacer commit y push de cambios (fecha y log)
        run: |
          git add *.txt *.log
          if git diff --cached --quiet; then
            echo "No hay cambios para hacer commit."
          else
            git commit -m "Visualización de tabla de datos en texto plano"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
