name: Ejecutar Script Seguridad CNS

on:
  schedule:
    - cron: '0 18 * * 1-5' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python main.py

      - name: Commit y push del archivo last_date.txt actualizado
        run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add last_date.txt
            git diff --cached --quiet && echo "No hay cambios para commitear" || git commit -m "Actualización de last_date.txt automática"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}

