name: Ejecutar Script Seguridad CNS

on:
  schedule:
    - cron: '0 18 * * 1-5'  # Ejecutar de lunes a viernes a las 12PM CDMX
  workflow_dispatch:

permissions:
  contents: write  # 👈 Esto da permiso para hacer commit/push

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python main.py

      - name: Subir archivo last_date.txt actualizado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Gustavo I. Castañeda
          author_email: github-actions@github.com
          message: "Actualización de last_date.txt automática"
          add: "last_date.txt"
